### ISSUE TITLE
Please consider node-red-contrib- naming guidelines

### ISSUE THREAD

**Issue by knolleary** [rnplus/node-red-node-hold#1]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

You're under no obligation to change the name, but I hope you'll consider it.

Many thanks, Nick

**Comment by renzenicolai** [comment]
Okay. I will change the package name soon.
Where can I find these packaging guidelines?

**Comment by knolleary** [comment]
Many thanks. You'll find the packaging guidelines here: http://nodered.org/docs/creating-nodes/packaging

**Comment by renzenicolai** [comment]
I created a new package for the node "node-red-contrib-hold" and
deprecated the old package. I can apparently not unpublish the "node-
red-node-hold" package since it is more than 24 hours old.

**Comment by knolleary** [comment]
Thanks. If you publish a new version of the old package name with the 'node-red' keyword removed, it will get removed from flows.nodered.org overnight (otherwise I can manually remove it).
